version: 0.2

phases:

  install:

    runtime-versions:

      dotnet: 6.0

  pre_build:

    commands:

      - dotnet restore webapp.csproj

  build:

    commands:

      - dotnet build webapp.csproj

  post_build:

    commands:

      - dotnet publish -c Release -o ./app/ webapp.csproj

artifacts:

  files:

    - '**/*'
